{% set name = "napari-assistant-plugin-generator" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-assistant-plugin-generator-{{ version }}.tar.gz
  sha256: ea33b52858288b1d739d807af6f28df25686703d86c951baf4ed0a3f77d03811

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8,<3.11.0a0
  run:
    - autopep8
    - cookiecutter
    - dask-core
    - jupyter
    - jupytext
    - magicgui
    - napari-assistant >=0.4.1
    - napari-plugin-engine >=0.1.4
    - napari-tools-menu
    - numpy !=1.19.4
    - python >=3.8,<3.11.0a0

test:
  imports:
    - napari_assistant_plugin_generator
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/napari-assistant-plugin-generator
  summary: Auto-generate python code from within napari to make napari-assistant compatible plugins
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/haesleinhuepf/napari-assistant-plugin-generator

extra:
  recipe-maintainers:
    - goanpeca
    - haesleinhuepf
    - jaimergp
